name: Allure postprocessing
description: Updates Allure test results
inputs:
  item-type:
    description: epic, story, etc
    required: true
    default: epic
  name:
    description: epic, story, etc name
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        cd openzeppelin-contracts/allure-results
        sed -i '.bak' 's+<labels/>+<labels><label><name>${{ inputs.item-type }}</name><value>${{ inputs.name }}</value></label></labels>+g' *.xml
      shell: bash
