name: Install Parallel and solc
description: Installs GNU Parallel and solc 0.8.3
runs:
  using: "composite"
  steps:
    - run: |
        npm install -g solc@0.8.3
        # sudo apt-get update
        # sudo apt install parallel
        brew install parallel
      shell: bash
