name: OpenZeppelin contracts preparation
description: Downloads the submodule, creates a folder for reports and put categories.json there
runs:
  using: "composite"
  steps:
    - run: |
        git submodule update --init --recursive
        cd openzeppelin-contracts
        git pull origin master
        echo "$ pwd"
        pwd
        cp ../hardhat.config.js .
      shell: bash
    - run: |
        cd openzeppelin-contracts
        ALLURE_RESULTS="allure-results"
        mkdir $ALLURE_RESULTS
        cp ../categories.json "./$ALLURE_RESULTS"
        echo "$ ls $ALLURE_RESULTS"
        ls $ALLURE_RESULTS
        echo "============================================================================================="
        echo "==================== the openzeppelin-contracts repo is downloaded =========================="
        echo "============================= and hardhat.config.js is here ================================="
        echo "============================================================================================="
        echo "$ ls -la"
        ls -la

      shell: bash




