name: OpenZeppelin contracts preparation
description: Downloads the submodule, creates a folder for reports and put categories.json there
runs:
  using: "composite"
  steps:
    - run: |
        git submodule update --init --recursive
        cd openzeppelin-contracts
        git pull origin master
        echo "$ pwd"
        pwd
        cp ../hardhat.config.js .
        cp ../get_private_keys.js .
      shell: bash




