name: Run Hardhat tests
description: Run all the tests from a subfolder of the test folder
inputs:
  folder-name:
    description: name of subfolder
    required: true
    default: ''
  jobsNumber:
    description: number of jobs runnign in parallel
    required: true
    default: '8'
runs:
  using: "composite"
  steps:
    - name: Display input parameters
      run: |
        echo "subfolder name = ${{ inputs.folder-name }}"
        echo "jobs number = ${{ inputs.jobsNumber }}"
      shell: bash
    - run: |
        cd openzeppelin-contracts
        # npx hardhat test
        # find "$(pwd)/test/${{ inputs.folder-name }}" | grep test.js | echo $_ | npx hardhat test $_
        # find "$(pwd)/test/${{ inputs.folder-name }}" | grep test.js | echo $_ | ../node_modules/.bin/hardhat test $_
        # the last working version
        # find "$(pwd)/test/${{ inputs.folder-name }}" | grep test.js | ../node_modules/.bin/hardhat test $_
        JOBS_NUMBER=${{ inputs.jobsNumber }}
        find "test/${{ inputs.folder-name }}" -name '*.js' | parallel --jobs $JOBS_NUMBER npx hardhat test {}
        echo "============================================================================================="
        echo "====================================== test results ========================================="
        echo "============================================================================================="
        echo "$ pwd"
        pwd
        echo "$ ls allure-results"
        ls allure-results
      shell: bash
